<!-- weather widget start -->
<div id="m-booked-vertical-one-prime-18577">
    <div class="weather-customize weather-booked-vertical-one-prime" style="width:160px;">
        <div class="booked-vertical-prime-in">
            <div class="booked-vertical-prime">
                <div class="bwop-city">Ho Chi Minh City</div>
                <div class="bwop-icon wm18 "></div>
                <div class="booked-bwop-today">
                    <div class="booked-bwop-today-temperature">
                        <div class="booked-wzs-bwop-val">
                            <div class="booked-bwop-number"><span class="plus">+</span>32</div>
                            <div class="booked-bwop-dergee">
                                <div class="booked-wzs-bwop-dergee-val">&deg;</div>
                                <div class="booked-wzs-bwop-dergee-name">C</div>
                            </div>
                        </div>
                    </div>
                    <div class="booked-bwop-today-extreme">
                        <div class="booked-bwop booked-pd-h"><span>High:</span><span class="plus">+</span>32</div>
                        <div class="booked-bwop booked-pd-l"><span>Low:</span><span class="plus">+</span>26</div>
                    </div>
                </div>
                <div class="bwop-state"> Rain </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var css_file = document.createElement("link");
    var widgetUrl = location.href;
    css_file.setAttribute("rel", "stylesheet");
    css_file.setAttribute("type", "text/css");
    css_file.setAttribute("href", 'https://s.bookcdn.com/css/w/booked-wzs-prime-vertical-one.css?v=0.0.1');
    document.getElementsByTagName("head")[0].appendChild(css_file);

    function setWidgetData_18577(data) {
        if (typeof(data) != 'undefined' && data.results.length > 0) {
            for (var i = 0; i < data.results.length; ++i) {
                var objMainBlock = document.getElementById('m-booked-vertical-one-prime-18577');
                if (objMainBlock !== null) {
                    var copyBlock = document.getElementById('m-bookew-weather-copy-' + data.results[i].widget_type);
                    objMainBlock.innerHTML = data.results[i].html_code;
                    if (copyBlock !== null) objMainBlock.appendChild(copyBlock);
                }
            }
        } else {
            alert('data=undefined||data.results is empty');
        }
    }
    var widgetSrc = "https://widgets.booked.net/weather/info?action=get_weather_info;ver=7;cityID=18408;type=7;scode=50243;ltid=3457;domid=w209;anc_id=75867;countday=undefined;cmetric=1;wlangID=1;color=137AE9;wwidth=160;header_color=ffffff;text_color=333333;link_color=08488D;border_form=1;footer_color=ffffff;footer_text_color=333333;transparent=0;v=0.0.1";
    widgetSrc += ';ref=' + widgetUrl;
    widgetSrc += ';rand_id=18577';
    var weatherBookedScript = document.createElement("script");
    weatherBookedScript.setAttribute("type", "text/javascript");
    weatherBookedScript.src = widgetSrc;
    document.body.appendChild(weatherBookedScript)
</script><!-- weather widget end -->